name: Justin.Brown
favicon: null
layout_spectrum: 0.11728939390741289
typography_spectrum: 0.2502713738940656
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0809'
    - '#f29c6f'
    - '#5c2916'
    - '#fafbee'
    - '#107b5f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
