name: Justin.Brown
favicon: null
layout_spectrum: 0.11728939390741289
typography_spectrum: 0.2502713738940656
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.022707474417984486
  lightness: 0.9596738014370203
  saturation: 0.0748859397135675
  rhythmicContrast: 0.45623164414428174
purpose: []
